### ISSUE TITLE
index out of bounds

### ISSUE THREAD

**Issue by przemekl** [CenterForMedicalGeneticsGhent/WisecondorX#15]
'WisecondorX predict' fails with message:
Traceback (most recent call last):
  File "/miniconda2/bin/WisecondorX", line 11, in <module>
    load_entry_point('WisecondorX==0.2.0', 'console_scripts', 'WisecondorX')()
  File "/miniconda2/lib/python2.7/site-packages/wisecondorX/main.py", line 531, in main
    args.func(args)
  File "/miniconda2/lib/python2.7/site-packages/wisecondorX/main.py", line 339, in tool_test
    inflated_z = inflate_array_multi(cleaned_z, mask_list)
  File "/miniconda2/lib/python2.7/site-packages/wisecondorX/wisetools.py", line 290, in inflate_array_multi
    temp = inflate_array(temp, mask)
  File "/miniconda2/lib/python2.7/site-packages/wisecondorX/wisetools.py", line 282, in inflate_array
    temp[i] = array[j]
IndexError: index 29123 is out of bounds for axis 0 with size 29123

**Comment by leraman** [comment]
Hi @przemekl 

Which WCX version are you using? Are you sure all of your samples are mapped vs the same human reference genome?

**Comment by przemekl** [comment]
I use version 0.2.0.
I did not have this type of problems with the previous version.
Yes, all samples are mapped against hg38

**Comment by przemekl** [comment]
Npz files and reference has been built from scratch using version 0.2.0.
I will check the possibility of sharing data

**Comment by leraman** [comment]
Hi @przemekl,

I recently stumbled upon this issue myself. It will be fixed from version v2.0.0 on.
