### ISSUE TITLE
Issue with numpy v1.16.3

### ISSUE THREAD

**Issue by woook** [CenterForMedicalGeneticsGhent/WisecondorX#42]
Hi, I'm getting the following reproducible error as of a few days ago:
`ValueError: Object arrays cannot be loaded when allow_pickle=False`

I think this is due to as a newer version of numpy (v1.16.3) is now brought in by conda, and there's a change in this version of numpy so that the default value for allow_pickle is now False (whereas it was True previously).

Is a fix possible? Or please point me in right direction and I can try to work up a patch?

Thanks.

**Comment by matthdsm** [comment]
Hi,

Thanks for the report. Could you include the full traceback? Thank would make debugging a lot more easy.

Thanks
M

**Comment by woook** [comment]
Let me know if you need more:

Traceback (most recent call last):
```
  File "/home/dnanexus/miniconda/bin/WisecondorX", line 12, in <module>
    sys.exit(main())
  File "/home/dnanexus/miniconda/lib/python2.7/site-packages/wisecondorX/main.py", line 371, in main
    args.func(args)
  File "/home/dnanexus/miniconda/lib/python2.7/site-packages/wisecondorX/main.py", line 49, in tool_newref
    sample = npzdata['sample'].item()
  File "/home/dnanexus/miniconda/lib/python2.7/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/dnanexus/miniconda/lib/python2.7/site-packages/numpy/lib/format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

**Comment by matthdsm** [comment]
Hi @woook 
I just pushed a commit that should fix your issue. Thanks for the pointer on the new defaults in numpy 1.16.
If you install the latest development version (using `setup.py`) you should be good to go!
Cheers
M

**Comment by woook** [comment]
Awesome, that was fast!
Thanks - will grab the dev version
