### ISSUE TITLE
WisecondorX crashed with incomplete segment information on chr23

### ISSUE THREAD

**Issue by MagdalenaFeldhahn** [CenterForMedicalGeneticsGhent/WisecondorX#58]
Dear WisecondorX Team. 

I tried to run WisecondorX on about 15 samples. 
It worked fine with the default binsize. 
I created a second reference with a binsize of 10000 bp. 
With the new reference, WiseconrodX crashed for 6 of the 15 smaples with the same error. Full error message see below. 
For these samples, no plots were generated and a file plot_tmp.json is leftofer in the results folder. 

These files seems to be incomplete, which probalbly explains the json sererialization error. 

Last line of one of them : 
.....[21, 1605, 5125, 1.161198643917641, 0.057], [22, 6, 5857, 6.4352679982391905, 0.0094], [22, 6167, 15527, -7.759932041734583, -0.0144], [23, 264, 1011, -0.1964148757639304, 0.0258], [23, 1309, 2882,   

All of the sample crash at chr23
I had a look at the segments.bed files.
They all have an unexpected entry for chrY : 

X	61670001	155270000	-0.0145	-7.747707792229975
Y	2640001	10110000	-0.0129	-1.31707509708712
Y	13090001	28820000	-0.0018	--
Y	58800001	59040000	0.0246	0.7273948943429487

(The segments with "--" insted of a float in column five differ, but all samples that crahed have one)

So I guess these segments cause the crash?  
Did you observe a similar behaviour before?  Do you have any idea what the problem might be?  

Only chrY seems to be the problem, the female samples all worked fine. But I also have 4 male samples that did not crash. 
Do you have any suggestions how to resolve this problem?  

Thank you very much in advance and best regards, 
Magdalena 

[INFO - 2020-07-29 08:53:59]: Writing plots ...
Traceback (most recent call last):
  File "/usr/local/bin/WisecondorX", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/wisecondorX/main.py", line 400, in main
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/wisecondorX/main.py", line 249, in tool_test
    exec_write_plots(rem_input, results)
  File "/usr/local/lib/python2.7/site-packages/wisecondorX/predict_output.py", line 31, in exec_write_plots
    exec_R(json_dict)
  File "/usr/local/lib/python2.7/site-packages/wisecondorX/overall_tools.py", line 61, in exec_R
    json.dump(json_dict, open(json_dict['infile'], 'w'))
  File "/usr/local/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/local/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/local/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/usr/local/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/local/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/local/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: masked is not JSON serializable

**Comment by leraman** [comment]
Hi @MagdalenaFeldhahn 

Thanks for the detailed description. We have seen this error before and planning a fix. You probably have too few reads for such a small bin size in chrY. In meantime, you could always blacklist  chrY using the --blacklist option, if Y is of no interest ofcourse. I'll keep you posted once fixed.

Best, Lennart

**Comment by MagdalenaFeldhahn** [comment]
Hi Lennart. 
Thank you for your quick reply! We will try blacklisting of chrY or increase the binsize a bit. 
Best, Magdalena
