### ISSUE TITLE
--plotyfrac encountered error

### ISSUE THREAD

**Issue by KhanhLPBao** [CenterForMedicalGeneticsGhent/WisecondorX#68]
I'm trying to determine y fraction cutoff but everytime I add --plotyfrac it always return this

> Traceback (most recent call last):
  File "/home/vm/.local/bin/WisecondorX", line 8, in <module>
    sys.exit(main())
  File "/home/vm/.local/lib/python3.8/site-packages/wisecondorX/main.py", line 405, in main
    args.func(args)
  File "/home/vm/.local/lib/python3.8/site-packages/wisecondorX/main.py", line 61, in tool_newref
    genders, trained_cutoff = train_gender_model(args, samples)
  File "/home/vm/.local/lib/python3.8/site-packages/wisecondorX/newref_tools.py", line 36, in train_gender_model
    ax.hist(y_fractions, bins=100, normed=True)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/__init__.py", line 1447, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/axes/_axes.py", line 6815, in hist
    p.update(kwargs)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/artist.py", line 996, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'Rectangle' object has no property 'normed'

Does it error comes from matplotlib version too high? I'm using matplotlib 3.3 because my python version is 3.8 and I cannot install 2.2.3 using pip. 
Also now I have more than 200 samples in .npz, does it neccessary to manually determine y fraction cutoff anymore?

**Comment by leraman** [comment]
Apperantly the 'normed' attribute in https://github.com/CenterForMedicalGeneticsGhent/WisecondorX/blob/master/wisecondorX/newref_tools.py#L36 has been removed in later matplotlib versions. You can use the cross-compatible 'density' attribute instead. I'll update the master soon.

**Comment by leraman** [comment]
When having 200 samples, gender prediction should be sufficiently accurate. You can always run the --plotyfrac function anyway and confirm the mimimum of the fit if you have any doubts.

**Comment by KhanhLPBao** [comment]
Thank you very much
