### ISSUE TITLE
Error while creating reference data

### ISSUE THREAD

**Issue by samchrist12** [CenterForMedicalGeneticsGhent/WisecondorX#71]
Hi WisecondorX team,

So I got an error while running this code
```
WisecondorX newref ./*.npz reference_output.npz
```
The error output that I get was
```
[INFO - 2021-01-18 13:47:20]: Creating new reference
[INFO - 2021-01-18 13:47:20]: Importing data ...
[INFO - 2021-01-18 13:47:20]: Loading: ./IDXX-022-0086.npz
[INFO - 2021-01-18 13:47:20]: Binsize: 5000
Traceback (most recent call last):
  File "/home/genomics/anaconda3/envs/wisecondor/bin/WisecondorX", line 10, in <module>
    sys.exit(main())
  File "/home/genomics/anaconda3/envs/wisecondor/lib/python2.7/site-packages/wisecondorX/main.py", line 400, in main
    args.func(args)
  File "/home/genomics/anaconda3/envs/wisecondor/lib/python2.7/site-packages/wisecondorX/main.py", line 58, in tool_newref
    samples.append(scale_sample(sample, binsize, args.binsize))
  File "/home/genomics/anaconda3/envs/wisecondor/lib/python2.7/site-packages/wisecondorX/overall_tools.py", line 30, in scale_sample
    new_len = int(np.ceil(len(chr_data) / float(scale)))
TypeError: object of type 'NoneType' has no len()
```
here is my .npz data, is there anything wrong with the data size ? because it is a lot smaller comparing with the BAM file.
I got this npz data by converting BAM file from SAM file that was the output of Bowtie2's mapping with a single read genome.
![image](https://user-images.githubusercontent.com/33079729/104953545-2d7fa180-59f9-11eb-9257-3206be8ae5e1.png)

Please help me,
Thanks

**Comment by KhanhLPBao** [comment]
Hi
Does your .bam file be sorted yet? Looks like it does not be sorted

**Comment by samchrist12** [comment]
> Hi
> Does your .bam file be sorted yet? Looks like it does not be sorted

Hi @KhanhLPBao 
Yeah my .bam file not sorted yet, so it need to be sorted first if I want to use it ? Whats the difference between the sorted and unsorted one, I'm new to this field so I don't know about it.

**Comment by leraman** [comment]
Hi @samchrist12 

.npz files are typically sized 500kb-1MB; therefore, something failed during the convert stage. I have not seen this error before, it has likely to do with the way your bam files are formatted. 

So unfortunately, there is not much I can do for you at this time. You might want to take a look at the code here, and check if the attributes used are present in your bam files, and if, e.g., the chromosome names match: https://github.com/CenterForMedicalGeneticsGhent/WisecondorX/blob/master/wisecondorX/convert_tools.py

**Comment by samchrist12** [comment]
Hi @leraman 

Thank you for responding to my question. From my investigation regarding the issue, the error `TypeError: object of type 'NoneType' has no len()` is because all my sample in my .npz file has None value.

I think this is because of the index that I use for creating the .bam file was wrong. Do you know how to create a right index for my data ?

Here is my current index fasta file
```
>A002
CGATGT
>A005
ACAGTG
>A007
CAGATC
>A012
CTTGTA
>A013
AGTCAA
>A014
AGTTCC
>A018
GTCCGC
>A019
GTGAAA
>A001
ATCACG
>A003
TTAGGC
>A008
ACTTGA
>A010
TAGCTT
>A020
GTGGCC
>A022
CGTACG
>A025
ACTGAT
```

**Comment by leraman** [comment]
The file you sent, is that your fasta reference during read mapping? Because that's not a human reference genome.

**Comment by samchrist12** [comment]
@leraman yea, that was the fasta reference that I use, hmm no wonder it doesn't work. I got that fasta file from my user, I personally don't understand about human genome so I don't know whether it was the right reference or not.

**Comment by abhijitswain62** [comment]
wisecondorX newref *.npz reference.npz --nipt --binsize 100000 --refsize 100 --cpus 8
[INFO - 2025-05-28 12:08:56]: Creating new reference
[INFO - 2025-05-28 12:08:56]: Importing data ...
[INFO - 2025-05-28 12:08:56]: Loading: CL10002L0141.npz
[INFO - 2025-05-28 12:08:56]: Binsize: 5000
[INFO - 2025-05-28 12:08:56]: Loading: CL10007L0165.npz
[INFO - 2025-05-28 12:08:56]: Binsize: 5000
[INFO - 2025-05-28 12:08:56]: Loading: CL10009L0160.npz
[INFO - 2025-05-28 12:08:56]: Binsize: 5000
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x75c4b452ff60>
Traceback (most recent call last):
  File "/home/genomiki/anaconda3/lib/python3.12/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/genomiki/anaconda3/lib/python3.12/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/genomiki/anaconda3/lib/python3.12/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/genomiki/anaconda3/lib/python3.12/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x75c4b452ff60>
Traceback (most recent call last):
  File "/home/genomiki/anaconda3/lib/python3.12/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/home/genomiki/anaconda3/lib/python3.12/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/genomiki/anaconda3/lib/python3.12/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "/home/genomiki/anaconda3/lib/python3.12/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/home/genomiki/anaconda3/bin/wisecondorX", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/genomiki/anaconda3/lib/python3.12/site-packages/wisecondorx/main.py", line 487, in main
    args.func(args)
  File "/home/genomiki/anaconda3/lib/python3.12/site-packages/wisecondorx/main.py", line 70, in tool_newref
    genders, trained_cutoff = train_gender_model(args, samples)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/genomiki/anaconda3/lib/python3.12/site-packages/wisecondorx/newref_tools.py", line 62, in train_gender_model
    cut_off = gmm_x[local_min_i][0]
              ~~~~~~~~~~~~~~~~~~^^^
IndexError: index 0 is out of bounds for axis 0 with size 0
sorry to open a issue but i get these error when try to create the reference
-rw-rw---- 1 genomiki genomiki 415K May 28 11:14 CL10002L0141.npz
-rw-rw---- 1 genomiki genomiki 424K May 28 11:15 CL10007L0165.npz
-rw-rw---- 1 genomiki genomiki 425K May 28 11:16 CL10009L0160.npz
