### ISSUE TITLE
IndexError When WisecondorX predict

### ISSUE THREAD

**Issue by qingyun039** [CenterForMedicalGeneticsGhent/WisecondorX#73]
Hi:
When I used WisecondorX predict, I got this err:

➜  ~ WisecondorX predict /data/home/chenshulin/project/Data/NIPT/6.npz/SRR597503                                                                  9.npz /data/home/chenshulin/project/Data/NIPT/6.npz/refs/reference_output.npz te                                                                  st --bed
[INFO - 2021-02-22 10:56:14]: Starting CNA prediction
[INFO - 2021-02-22 10:56:14]: Importing data ...
[INFO - 2021-02-22 10:56:14]: Normalizing autosomes ...
[INFO - 2021-02-22 10:56:24]: Normalizing gonosomes ...
Traceback (most recent call last):
  File "/data/home/chenshulin/.local/bin/WisecondorX", line 33, in <module>
    sys.exit(load_entry_point('WisecondorX==1.2.1', 'console_scripts', 'WisecondorX')())
  File "/data/home/chenshulin/.local/lib/python3.9/site-packages/WisecondorX-1.2.1-py3.9.egg/wisecondorX/main.py", line 404, in main
    args.func(args)
  File "/data/home/chenshulin/.local/lib/python3.9/site-packages/WisecondorX-1.2.1-py3.9.egg/wisecondorX/main.py", line 229, in tool_test
    results[result] = get_post_processed_result(
  File "/data/home/chenshulin/.local/lib/python3.9/site-packages/WisecondorX-1.2.1-py3.9.egg/wisecondorX/predict_control.py", line 43, in get_post_processed_result
    result[infinite_mask] = 0
IndexError: boolean index did not match indexed array along dimension 0; dimension is 28525 but corresponding boolean dimension is 28526

**Comment by leraman** [comment]
Hi @qingyun039 

I'm not sure what triggers this error. Probably (?) unrelated, but there is a space 'test'.

How much samples are in your reference? Is it a --nipt reference?

Best
