### ISSUE TITLE
WisecondorX newref

### ISSUE THREAD

**Issue by smruti241** [CenterForMedicalGeneticsGhent/WisecondorX#78]
When I am running wisecondorX newref command, it is giving me following error:
(smruti) mdrcubuntu@mdrcubuntu-H110M-H:~/Downloads$ WisecondorX newref NIPT/*.npz NIPT/reference_output.npz --nipt --binsize 100000 --refsize 100 --cpus 8
[INFO - 2021-04-16 17:44:12]: Creating new reference
[INFO - 2021-04-16 17:44:12]: Importing data ...
[INFO - 2021-04-16 17:44:12]: Loading: NIPT/sample_006.npz
[INFO - 2021-04-16 17:44:12]: Binsize: 50000
Traceback (most recent call last):
  File "/home/mdrcubuntu/anaconda3/envs/smruti/bin/WisecondorX", line 10, in <module>
    sys.exit(main())
  File "/home/mdrcubuntu/anaconda3/envs/smruti/lib/python3.9/site-packages/wisecondorX/main.py", line 404, in main
    args.func(args)
  File "/home/mdrcubuntu/anaconda3/envs/smruti/lib/python3.9/site-packages/wisecondorX/main.py", line 58, in tool_newref
    samples.append(scale_sample(sample, binsize, args.binsize))
  File "/home/mdrcubuntu/anaconda3/envs/smruti/lib/python3.9/site-packages/wisecondorX/overall_tools.py", line 31, in scale_sample
    new_len = int(np.ceil(len(chr_data) / float(scale)))
TypeError: object of type 'NoneType' has no len()

I have aligned the fastq files against reference genome and then sorted the bam file using picard sortsam. But still I am getting this error. my npz files are in bytes. I dont know if there is any issue in wisecondor convert or newref process. Please help me regarding this. Thank you in advance.

**Comment by smruti241** [comment]
(smruti) mdrcubuntu@mdrcubuntu-H110M-H:~/Downloads/NIPT/new_data$ WisecondorX newref *.npz reference_output.npz --nipt --binsize 100000
[INFO - 2021-04-19 16:07:26]: Creating new reference
[INFO - 2021-04-19 16:07:26]: Importing data ...
[INFO - 2021-04-19 16:07:26]: Loading: sample_006.npz
[INFO - 2021-04-19 16:07:26]: Binsize: 5000
Traceback (most recent call last):
  File "/home/mdrcubuntu/anaconda3/envs/smruti/bin/WisecondorX", line 10, in <module>
    sys.exit(main())
  File "/home/mdrcubuntu/anaconda3/envs/smruti/lib/python3.9/site-packages/wisecondorX/main.py", line 404, in main
    args.func(args)
  File "/home/mdrcubuntu/anaconda3/envs/smruti/lib/python3.9/site-packages/wisecondorX/main.py", line 58, in tool_newref
    samples.append(scale_sample(sample, binsize, args.binsize))
  File "/home/mdrcubuntu/anaconda3/envs/smruti/lib/python3.9/site-packages/wisecondorX/overall_tools.py", line 31, in scale_sample
    new_len = int(np.ceil(len(chr_data) / float(scale)))
TypeError: object of type 'NoneType' has no len()

Today I ran it again and getting the same thing. Please help me regarding this.

**Comment by wyj-lzu** [comment]
Hi！ I meet the same error. Have you fixed it ?

**Comment by leraman** [comment]
Hi,

It's difficult to say what's going on. I'm guessing something went wrong during the covert stage. Would you mind sending a .npz file resulting from the convert stage?

Best

**Comment by leraman** [comment]
@matthdsm might be related to the recent changed in the convert phase?

**Comment by matthdsm** [comment]
There's no difference in the conversion, only an extra file format thats supported, pysam converts the data all the same

**Comment by wyj-lzu** [comment]
[AS16.zip](https://github.com/CenterForMedicalGeneticsGhent/WisecondorX/files/6349266/AS16.zip)
This is my file. @leraman

**Comment by leraman** [comment]
@smruti241 @wyj-lzu,

Could you also send your convert command?

**Comment by wyj-lzu** [comment]
#!/bin/bash

# PARAMETERS
mkdir converts
BAM_FILES="bam_files.txt" # file
# Example of the structure of this file:
# ID_1 path/to/ID_1.bam
# ID_2 path/to/ID_2.bam
# ...
OUTPUT_DIR="./converts" # existing folder

# SCRIPT

while read LINE; do
        SAMPLE=$(echo $LINE | awk -F ' ' '{print $1}')
        BAM=$(echo $LINE | awk -F ' ' '{print $2}')
        echo "Creating 5kb bins for sample ${SAMPLE}"
        WisecondorX convert ${BAM} ${OUTPUT_DIR}/${SAMPLE}.npz

done < ${BAM_FILES}

**Comment by wyj-lzu** [comment]
#!/bin/bash

## PARAMETERS
mkdir converts
BAM_FILES="bam_files.txt" # file
## Example of the structure of this file:
## ID_1 path/to/ID_1.bam
## ID_2 path/to/ID_2.bam
## ...
OUTPUT_DIR="./converts" # existing folder

##SCRIPT

while read LINE; do
        SAMPLE=$(echo $LINE | awk -F ' ' '{print $1}')
        BAM=$(echo $LINE | awk -F ' ' '{print $2}')
        echo "Creating 5kb bins for sample ${SAMPLE}"
        WisecondorX convert ${BAM} ${OUTPUT_DIR}/${SAMPLE}.npz

done < ${BAM_FILES}

**Comment by leraman** [comment]
@wyj-lzu 

Apparently your .npz files are empty. Could you post your command for a single bam file conversion and the resulting stdout?

**Comment by smruti241** [comment]
> Hi！ I meet the same error. Have you fixed it ?

No not yet

**Comment by wyj-lzu** [comment]
My bam_files.txt is like this :
AS16    AS16.sort.bam 
But my bam file was got from bwa, samtools sort and samtools index. Is this right?

**Comment by smruti241** [comment]
@leraman I used wisecondorX convert bam filename npz output name --binsize 5000

**Comment by smruti241** [comment]
I did alignment using BWA and sort the Sam file using Picard and conversion too from Picard. After Picard the bam file was  nearly 2.5 GB. After conversion, I am getting npz files in bytes

**Comment by leraman** [comment]
I'm still not sure what went wrong. Some stuff for you to test:
- your format is actually bam, and not sam with a '.bam' extension
- the indexing ('.bam.bai') is executed on the final bam files you've obtained
- your chromosomes are formated as '1' or 'chr1'
- you are using a classic human reference genome during mapping (GRCh38 or GRCh37; hg38 or hg19)

**Comment by smruti241** [comment]
Yeah I am using GRch37 human reference genome. Which reference genome should I use then?

**Comment by leraman** [comment]
Your reference genome is fine.

**Comment by leraman** [comment]
If you've completed the above checklist, you might also want to update WisecondorX using

`pip install -U git+https://github.com/CenterForMedicalGeneticsGhent/WisecondorX`

**Comment by wyj-lzu** [comment]
Is the program sign for human?

**Comment by leraman** [comment]
yes.

**Comment by matthdsm** [comment]
Yes, this program was designed to be used with human genomes and only human genomes

**Comment by smruti241** [comment]
Still its not working. I have updated it too. I dont know why I am getting error again and again

**Comment by smruti241** [comment]
I think there is something wrong during conversion process. My bam files size lies between 2 GB to 2.5 GB. It should work

**Comment by wyj-lzu** [comment]
@leraman @matthdsm  OK I, got it. Thanks

**Comment by smruti241** [comment]
@wyj-lzu did you get the problem?

**Comment by smruti241** [comment]
@wyj-lzu did you solve the problem? Please let me know

**Comment by smruti241** [comment]
I am still stuck to the same problem

**Comment by bnouyou** [comment]
Hello,
I don't know if it could help but, I have used Bowtie2 for the alignment and then Bamsomadup for sorting and marking duplicates. Then I use the convert function to create the npz file. With this process I have no problem with the npz file.

**Comment by smruti241** [comment]
@bnouyou thank you. It would be very helpful if you provide me commands so that I can also test once.

**Comment by smruti241** [comment]
@bnouyou  please provide me bowtie2 commands so that I can run it without any error

**Comment by matthdsm** [comment]
we use the following command to align our data

```bash
bowtie2 --no-unal --fast-local -p 4 --local \
-x /references/9606/GRCh38/bowtie2/GRCh38 \
-U sample.fastq.gz \
| bamsormadup inputformat=sam threads=4 SO=coordinate outputformat=bam level=0 \
| samtools view -1 -@ 3 -bhS -o alignments.bam
samtools index alignments.bam
```

Please note that it does *not* matter which aligner you use, as long as you use the same one across all the reference samples and during the actual analysis.

**Comment by smruti241** [comment]
I am facing the same issue. What to do I dont understand. Even bowtie2 alone is not working. bowtie2-align is also not working. I tried with bwasw, bwa aln and bwa mem. None has worked out. Please give me suggestions

**Comment by smruti241** [comment]
I am unable to load that output because it is a npz file consisting of npy file.

**Comment by smruti241** [comment]
my bam file is of 3.7 G and fastq files are of 5-6 G size. They are not empty. reads are there. I used this command:
bwa mem -Y -M -R "@RG\tID:10200106485\tLB:10200106485\tPL:ILLUMINA\tPM:HISEQ\tSM:10200106485" GRCh37_latest_genomic.fna IonXpress_006_NIPT_165_2021-03-25T10%3A31%3A30Z.fastq > aligned_reads.sam

java -jar gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar SortSam -I new_data/aligned_reads.sam -O new_data/aligned_reads.bam --SORT_ORDER coordinate --CREATE_INDEX True

WisecondorX convert aligned_reads.bam sample.npz --binsize 5000

WisecondorX newref *.npz reference_output.npz --nipt --binsize 100000

**Comment by smruti241** [comment]
K7O07:09907:09141	0	NC_000001.10	4608836	60	163M	*	0	0	TACAGTCTCTTTGATCGATCACAACATGAAGGCCTTTGCTTCAGGCACTCTGCTCTAAAGTCTGGCTGGATTTTCTGCAGGAAAGTAGAACTTATTTGGGAAAACATTGGAGGGGCATTTGCTGCTCAGCAGTGGCCTGCAAGATAGGTTGAAATCTCAACCC	287888;<<>D6878;9^C

**Comment by leraman** [comment]
```
        chr_name = chr
        if chr_name[:3].lower() == 'chr':
            chr_name = chr_name[3:]
        if chr_name not in bins_per_chr and chr_name != 'X' and chr_name != 'Y':
            continue
```

I'm guessing the convert 'continues' since your chromosome names are wronly formatted. Should be either '1' or 'chr1'

**Comment by smruti241** [comment]
yeah actually my format is wrong. How can i rectify it in bam file or fastq file?

**Comment by leraman** [comment]
Map against a valid reference genome, such as GRCh38

**Comment by smruti241** [comment]
but reference genome used is GRCh37 in my company. I cant use GRCh38

**Comment by matthdsm** [comment]
You can download a valid GRCh37/hg19 reference fasta from either Ensembl or UCSC.
